blank_issues_enabled: true
contact_links:
  - name: Respectful on the project
    url: https://codepen.io/Monredo/project/full/DKoNyj
    about: Do you have a comment, feedback, questions or concerns? Please comment below at the "Text Editor" project.
